version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres_Contaner
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5032:5032"
    networks:
      - webapinetwork
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_Container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - webapinetwork
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:
  redis:
  logs:

networks:
  webapinetwork:
    driver: bridge

   